### ISSUE TITLE
Bug: Missing `views` count in the Downloads & Resources section

### ISSUE THREAD

**Issue by estebanruseler** [GSA/ckanext-datagovcatalog#10]
### Description
on the dataset metadata page, the Downloads and Resources section is missing the `views` count 

**Environment:** [sandbox catalog](https://catalog-next.sandbox.datagov.us/dataset)

**Screenshots**
![](https://i.imgur.com/Eiw9I59.png)
![](https://i.imgur.com/wvHDyu2.png)

### How to reproduce
1. Visit the [Data page](https://catalog-next.sandbox.datagov.us/dataset) of the sandbox catalog
2. visit this dataset - [Total Number Black Lung Beneficiaries FY 2004 - Present](https://catalog-next.sandbox.datagov.us/dataset/total-number-black-lung-beneficiaries-fy-2004-present); the metadata page for the dataset gets loaded
3. Scroll to the `Downloads & Resources` section
4. observe that the `views` count is missing

### Expected behavior
- the dataset metadata page has an `views` count in the Downloads & Resources section
- The expected behavior can be [observed here](https://catalog.data.gov/dataset/total-number-black-lung-beneficiaries-fy-2004-present)

**Comment by adborden** [comment]
I think the views statistics depends on the CKAN tracking feature, which is disabled on production due to https://github.com/GSA/datagov-deploy/issues/1478. I think we can ignore this for now.
