### ISSUE TITLE
Small UI bug: Missing`search datasets in collections` is displayed as a link

### ISSUE THREAD

**Issue by estebanruseler** [GSA/ckanext-datagovcatalog#11]
### Description
for datasets flagged as collections, their metadata page contains a `Collection` section. This section enables the user to view datasets that are members of the Collection.
However, the `search datasets in this collection` UI (contained in this section) is displayed as a link as opposed to a button.

**Environment:** [sandbox catalog](https://catalog-next.sandbox.datagov.us/dataset)
**Screenshot**
![](https://i.imgur.com/F6lazD6.png)
![](https://i.imgur.com/FZbdfxr.png)

### How to reproduce
1. Visit the [Data page](https://catalog-next.sandbox.datagov.us/dataset) of the sandbox catalog
2. visit this dataset - [Organizational Development Survey of Civil Society Organizations in Moldova (2014-2015)](https://catalog-next.sandbox.datagov.us/dataset/organizational-development-survey-of-civil-society-organizations-in-moldova-2014-2015); the metadata page for the dataset gets loaded
3. Scroll to the `Collection` section
4. observe that `search datasets within this collection` is displayed as a link

### Expected behavior
- the `Collection` section of the dataset metadata page contains a **clickable button** with the label - `search datasets within this collection` 
- clicking on this button should load a page displaying the number and list of datasets contained in the collection.
- The expected behavior can be [observed here](https://catalog.data.gov/dataset/organizational-development-survey-of-civil-society-organizations-in-moldova-2014-2015)

**Comment by kimwdavidson** [comment]
@avdata99: when i go here: https://catalog-next.sandbox.datagov.us/dataset/organizational-development-survey-of-civil-society-organizations-in-moldova-2014-2015 i'm still seeing the text instead of a button. am i looking in the right place?

**Comment by avdata99** [comment]
> @avdata99: when i go here: https://catalog-next.sandbox.datagov.us/dataset/organizational-development-survey-of-civil-society-organizations-in-moldova-2014-2015 i'm still seeing the text instead of a button. am i looking in the right place?

It seems the deploy take more time. Now it's ok @kimwdavidson: 

![image](https://user-images.githubusercontent.com/3237309/91600107-c70cc080-e93d-11ea-9794-0c23acaff42a.png)

**Comment by kimwdavidson** [comment]
Looks good!
