### ISSUE TITLE
BUG: Missing `link is ok` affirmation in the Resource metadata page

### ISSUE THREAD

**Issue by estebanruseler** [GSA/ckanext-datagovcatalog#12]
### Description

Linked to [BUG: Missing `link is ok` affirmation in the Downloads & Resources section](https://github.com/GSA/datagov-ckan-multi/issues/391)

The metadata page for dataset resources is missing the `link is ok` affirmation

**Environment:** [sandbox catalog](https://catalog-next.sandbox.datagov.us/dataset)
**Screenshot**
![](https://i.imgur.com/5AWpN7G.png)
![](https://i.imgur.com/YPQi3Qi.png)

### How to reproduce
1. Visit the [Data page](https://catalog-next.sandbox.datagov.us/dataset) of the sandbox catalog
2. visit this dataset - [Mine Inspections](https://catalog-next.sandbox.datagov.us/dataset/mine-inspections); the metadata page for the dataset gets loaded
3. Scroll to the `Downloads & Resources` section and click on the resource title: [DOL API](https://catalog-next.sandbox.datagov.us/dataset/mine-inspections/resource/d47227b9-5289-4c74-b7ff-f3dda3c6f426); the resource metadata page gets loaded
4. observe that the `link is ok` affirmation message is missing

### Expected behavior
- the resource metadata page has a `link is ok` affirmation message 
- The expected behavior can be [observed here](https://catalog.data.gov/dataset/mine-inspections/resource/3f20c195-34ae-4c3a-a118-7d80c065b335)

**Comment by adborden** [comment]
Similar to https://github.com/GSA/ckanext-datagovcatalog/issues/9#issuecomment-677829706, I think this comes from the qa worker which is not enabled in sandbox. We should take another look at this on staging.

**Comment by avdata99** [comment]
Related to [Multi#391](https://github.com/GSA/datagov-ckan-multi/issues/391)

**Comment by avdata99** [comment]
Before QA is required to run `archiver` and `qa` workers in the environment

**Comment by avdata99** [comment]
Moved to blocked since we are not able to QA them until we finish [Multi#417](https://github.com/GSA/datagov-ckan-multi/issues/417) and  [Deploy#2123](https://github.com/GSA/datagov-deploy/issues/2123)

**Comment by thejuliekramer** [comment]
You can verify this on [staging](https://admin-catalog-next-datagov.dev-ocsit.bsp.gsa.gov/dataset/mine-inspections)

**Comment by thejuliekramer** [comment]
Icons are missing - tracking that issue here https://github.com/GSA/ckanext-datagovcatalog/issues/14

**Comment by thejuliekramer** [comment]
Re-opening this because the link check is always [inconclusive](https://catalog-next.sandbox.datagov.us/dataset/terra-modis-regional-4m-day-night-sea-surface-temperature-sst4-near-real-time-nrt/resource/d1205017-3ddd-423e-abac-d1781b877a45) - we need to add some configuration for the upstream version of [ckanext-archiver](https://github.com/ckan/ckanext-archiver#using-archiver) specifically ckanext-archiver.cache_url_root = URL

reference link: https://github.com/ckan/ckanext-archiver/blob/master/ckanext/archiver/tasks.py#L609:L609

**Comment by thejuliekramer** [comment]
Additional issue: the db commands to init db for ckanext-qa, ckanext-archiver and ckanext-report are not running automatically

**Comment by thejuliekramer** [comment]
Link is ok is now working https://catalog-next.sandbox.datagov.us/dataset/terra-modis-regional-4m-day-night-sea-surface-temperature-sst4-near-real-time-nrt/resource/d1205017-3ddd-423e-abac-d1781b877a45

**Comment by thejuliekramer** [comment]
Icon is not loading - update was made already in datagovtheme - pending release but blocked by catalog build failing due to datapusher error

**Comment by thejuliekramer** [comment]
Working here in sandbox https://catalog-next.sandbox.datagov.us/dataset/terra-modis-regional-4m-day-night-sea-surface-temperature-sst4-near-real-time-nrt/resource/d1205017-3ddd-423e-abac-d1781b877a45
