### ISSUE TITLE
Fix Archiver Link Icons

### ISSUE THREAD

**Issue by thejuliekramer** [GSA/ckanext-datagovcatalog#14]
Icons in link checks are not showing up.

Expected Behavior:

<img width="250" alt="Screen Shot 2020-09-21 at 12 27 51 PM" src="https://user-images.githubusercontent.com/7378770/93800217-e24db180-fc05-11ea-82e9-f29981d646e2.png">

Actual Behavior:

<img width="243" alt="Screen Shot 2020-09-21 at 12 24 38 PM" src="https://user-images.githubusercontent.com/7378770/93800022-9569db00-fc05-11ea-93d1-089376f5076e.png">

**Comment by thejuliekramer** [comment]
Fixed on sandbox https://catalog-next.sandbox.datagov.us/dataset/mine-inspections/resource/d47227b9-5289-4c74-b7ff-f3dda3c6f426 

<img width="195" alt="Screen Shot 2020-09-22 at 10 38 52 AM" src="https://user-images.githubusercontent.com/7378770/93904951-053c9c00-fcc0-11ea-9a20-01200ce96e0c.png">

**Comment by adborden** [comment]
Looks good, thanks!
