### ISSUE TITLE
Update Tracking Information in Production

### ISSUE THREAD

**Issue by thejuliekramer** [GSA/ckanext-datagovcatalog#20]
Do we want to run this automatically with a cron job or manually?

Related to https://github.com/GSA/ckanext-datagovcatalog/issues/10

**Comment by thejuliekramer** [comment]
curl command working from inside server 

<img width="1449" alt="Screen Shot 2020-11-13 at 11 09 03 AM" src="https://user-images.githubusercontent.com/7378770/99099894-b06f2080-25a0-11eb-9c96-4038aafedadd.png">

**Comment by avdata99** [comment]
Tracking is enabled but it's failing when we call it from web

![image](https://user-images.githubusercontent.com/3237309/99099670-89711880-25b9-11eb-9d58-2f6c2e66d6db.png)

**Comment by avdata99** [comment]
[Here](https://github.com/GSA/datagov-deploy/blob/develop/ansible/roles/software/ckan/fix-ckan-tracking/tasks/main.yml#L3:L20) we update the URLs to point to the _writable_ instance

**Comment by avdata99** [comment]
This should work but it's failing (prefix **admin-** added to point the writable instance).
```
curl https://admin-catalog-next.data.gov/_tracking -d "url/dataset/department-for-the-aging-dfta-geriatric-mental-health-contracted-providers&type=page"
```

The URL is not been updated with ansible because JS code changed.

![image](https://user-images.githubusercontent.com/3237309/99104907-64cc6f00-25c0-11eb-9228-903d0f9eaa8b.png)

**Comment by avdata99** [comment]
[This test](https://github.com/GSA/datagov-deploy/blob/develop/ansible/roles/software/ckan/fix-ckan-tracking/molecule/default/tests/test_default.py#L24:L24) should be failing.

![image](https://user-images.githubusercontent.com/3237309/99105964-3d76a180-25c2-11eb-9a35-dea2ad85b01f.png)

The [JS file](https://catalog-next.data.gov/fanstatic/base/:version:2020-11-12T18:31:13.91/tracking.min.js) is not updated.
You wrote this test @FuhuXia. Did you remember this working?

**Comment by avdata99** [comment]
Working in sandbox, failing in production.
Required to check production logs

![image](https://user-images.githubusercontent.com/3237309/99264933-dcd4a800-27ff-11eb-8d7e-4a43e4e076eb.png)

**Comment by FuhuXia** [comment]
@avdata99 the JS code rewrite is working, but I would be glad to see it is replaced by POST redirecting.

**Comment by thejuliekramer** [comment]
The command is `ckan tracking update`

**Comment by thejuliekramer** [comment]
The tracking update feature is working in production 

<img width="669" alt="Screen Shot 2020-12-08 at 10 25 18 AM" src="https://user-images.githubusercontent.com/7378770/101510573-ba860400-393f-11eb-91c1-c858af51a290.png">

We manually increased the views to test - eventually this task will need to be run to update the views after the site goes live.

Do we want to set this up as a cron job or run manually once a month (or different period of time) 

There is a worker here https://github.com/GSA/datagov-deploy/blob/develop/ansible/roles/software/ckan/catalog/ckan-app/templates/supervisord_misc_worker.conf.j2#L71:L71
