### ISSUE TITLE
Bug: Missing "Harvested From" link

### ISSUE THREAD

**Issue by estebanruseler** [GSA/ckanext-datagovcatalog#7]
### Description
Datasets that have been migrated to the sandbox catalog are missing "Harvested From"  link on their metadata page. The `Harvested From` link provides a URL to the source of the dataset

**Environment:** [sandbox catalog](https://catalog-next.sandbox.datagov.us/dataset)
**Screenshot**
![](https://i.imgur.com/rjDXjNk.png)

### How to reproduce
1. Visit the [Data page](https://catalog-next.sandbox.datagov.us/dataset) of the sandbox catalog
2. click on any available dataset e.g. [FY2019 Federal Cybersecurity R&D Strategic Plan Implementation Roadmap](https://catalog-next.sandbox.datagov.us/dataset/fy2019-federal-cybersecurity-rd-strategic-plan-implementation-roadmap); the metadata page for the dataset gets loaded
3. observe that metadata page lacks a `Harvested From` link

### Expected behavior
- the metadata page for the dataset should contain a `Harvested From` link.
- The expected behavior can be [observed here](https://catalog.data.gov/dataset/fy2019-federal-cybersecurity-rd-strategic-plan-implementation-roadmap)

**Comment by avdata99** [comment]
Related to [Multi#373](https://github.com/GSA/datagov-ckan-multi/issues/373)

**Comment by kimwdavidson** [comment]
![Screen Shot 2020-08-30 at 10 32 24 PM](https://user-images.githubusercontent.com/22527532/91677442-b19bc000-eb10-11ea-8a63-bf60a8ad26e2.png)
