### ISSUE TITLE
Bug: Maintainer Email is displayed as the maintainer's name

### ISSUE THREAD

**Issue by estebanruseler** [GSA/ckanext-datagovcatalog#8]
### Description

*This is a bug in that the sandbox UI is different to production. But this is probably fine. I'm raising it so that it can be considered.*

The datasets that have been migrated to the sandbox catalog have a `Maintainer Email` displayed on the metadata page. However, the maintainer email is being displayed as a clickable *mailto* link of the `Maintainer Name` as opposed to displaying the maintainer's email addresss as a clickable *mailto* link

**Environment:** [sandbox catalog](https://catalog-next.sandbox.datagov.us/dataset)
**Screenshot**
![](https://i.imgur.com/t6r8ilc.png)

### How to reproduce
1. Visit the [Data page](https://catalog-next.sandbox.datagov.us/dataset) of the sandbox catalog
2. visit this dataset - [Current Population Survey - Marital and Family Labor Force Statistics](https://catalog-next.sandbox.datagov.us/dataset/current-population-survey-marital-and-family-labor-force-statistics); the metadata page for the dataset gets loaded
3. Scroll to the `Additional Metadata` section
4. observe that the `Maintainer Email` is displayed as a clickable mailto link of maintainer's name

### Expected behavior
- the `Maintainer Email` is displayed as a clickable email address of the maintainer
- The expected behavior can be [observed here](https://catalog.data.gov/dataset/current-population-survey-marital-and-family-labor-froce-statistics)

**Comment by adborden** [comment]
👍 I feel like this isn't MVP, but I feel like we'd still like to combine/cleanup the fields so that the name is displayed with the mailto link.

**Comment by kimwdavidson** [comment]
@avdata99: when i go here: https://catalog-next.sandbox.datagov.us/dataset/current-population-survey-marital-and-family-labor-force-statistics i'm still seeing the contact email as a name. am i looking in the right place?

**Comment by avdata99** [comment]
> @avdata99: when i go here: https://catalog-next.sandbox.datagov.us/dataset/current-population-survey-marital-and-family-labor-force-statistics i'm still seeing the contact email as a name. am i looking in the right place?

The deploy now it's finished and works

![image](https://user-images.githubusercontent.com/3237309/91600269-105d1000-e93e-11ea-8ebd-1302a765e675.png)

**Comment by kimwdavidson** [comment]
Looks good!
