### ISSUE TITLE
Bug: Missing `openness rating` in the Downloads & Resources section

### ISSUE THREAD

**Issue by estebanruseler** [GSA/ckanext-datagovcatalog#9]
### Description
on the dataset metadata page, the Downloads and Resources section is missing the `openness rating` 

**Environment:** [sandbox catalog](https://catalog-next.sandbox.datagov.us/dataset)
**Screenshots**
![](https://i.imgur.com/CflFZVH.png)
![](https://i.imgur.com/Q9HU2ny.png)

### How to reproduce
1. Visit the [Data page](https://catalog-next.sandbox.datagov.us/dataset) of the sandbox catalog
2. visit this dataset - [Mine Inspections](https://catalog-next.sandbox.datagov.us/dataset/mine-inspections); the metadata page for the dataset gets loaded
3. Scroll to the `Downloads & Resources` section
4. observe that the `openness rating` affirmation is missing

### Expected behavior
- the dataset metadata page has an `openness rating` in the Downloads & Resources section
- The expected behavior can be [observed here](https://catalog.data.gov/dataset/mine-inspections)

**Comment by adborden** [comment]
I think this comes down to environmental drift. The openness score comes from the the qa worker, which is not configured in sandbox. I suggest we take a look at this on staging before investigating further.

**Comment by avdata99** [comment]
Related to [Multi#391](https://github.com/GSA/datagov-ckan-multi/issues/391) and #12

**Comment by avdata99** [comment]
Before QA is required to run `archiver` and `qa` workers in the environment

**Comment by avdata99** [comment]
Moved to blocked since we are not able to QA them until we finish [Multi#417](https://github.com/GSA/datagov-ckan-multi/issues/417) and  [Deploy#2123](https://github.com/GSA/datagov-deploy/issues/2123)

**Comment by thejuliekramer** [comment]
You can verify this on [staging](https://admin-catalog-next-datagov.dev-ocsit.bsp.gsa.gov/dataset/mine-inspections)
